(executable
 (name oxcaml_validate)
 (modules oxcaml_validate)
 (libraries stdlib_upstream_compatible)
 (ocamlopt_flags (:standard -extension layout_poly -O3))
 (modes native))

(executable
 (name sha256_tests)
 (modules sha256 sha256_tests)
 (libraries stdlib_upstream_compatible)
 (ocamlopt_flags (:standard -extension layout_poly -O3))
 (modes native))

(executable
 (name benchmark_sha256)
 (modules sha256 benchmark_sha256)
 (libraries stdlib_upstream_compatible unix)
 (ocamlopt_flags (:standard -extension layout_poly -O3))
 (modes native))
